import { Inter } from 'next/font/google'

import "./globals.css";



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      
      
      <body >
      <div  className="header">
        <header >
          <h1 className={inter.className}>
            Malla vial
          </h1>
        </header>
      </div>
          {children}
         
      </body>
    </html>
  );
}
